---
title: "NFDI4Ing Data Collections Explorer"
author: "KIT / SCC"
date: "19/07/2023"
output:   
    flexdashboard::flex_dashboard:
        theme: spacelab
        orientation: columns
        vertical_layout: scroll
        logo: NFDI4Ing.png
        favicon: cropped-signet-32x32.png
        includes:
            after_body: footer.html
runtime: shiny
---
<!-- From StackOverflow question 51600940; this seems to be the easiest solution -->
<script>
$('.navbar-logo').wrap('<a href="https://www.nfdi4ing.de">');
</script>

```{r global, include=FALSE}
library(flexdashboard)
library(DT)
library(readr)

# Construct a HTML link; the destination is opened in a new tab/window
createLink <- function(name, link) {
  sprintf('<a href="%s" target="_blank">%s</a>', link, name)
}

Repositories <- read_delim("Repositories.csv",
    ";", escape_double = FALSE, trim_ws = TRUE, col_types = "c")

# Force the `Dataset size limit (GB)` to numeric; this ensures proper sorting
Repositories$`Dataset size limit (GB)` <- as.numeric(Repositories$`Dataset size limit (GB)`)

# Add a link to the repository to the name
Repositories$Name <- createLink(Repositories$Name, Repositories$URL)
```

Row {} 
--------------------------------------
#### Select
```{r selection}
# Create a drop down menu where entries after "All" are sorted
# alphabetically
createDDM <- function(Width, InputId, Label, TableColumnName) {
  column(Width,
         selectInput(InputId, Label,
                     c("All", sort(unique(as.character(TableColumnName))))))
}

fluidRow(
  createDDM(3, 'Institution', 'Hosting Institution:', Repositories$`Hosting Institution`),
  createDDM(3, 'Type', 'Type:', Repositories$Type),
  createDDM(3, 'Subject', 'Subject Area:', Repositories$`Subject area`),
  createDDM(3, 'Access', 'Open Access:', Repositories$`Open Access`),
  title = "NFDI4Ing Repository Explorer"
)
```

#### Repositories and Collections
```{r rendering}
div(DT::dataTableOutput('repos'), style = "font-size: 100%")
output$repos <- DT::renderDataTable(DT::datatable({
  # Do not display the URL column
  data <- Repositories[c(1:8,10)]
  if (input$Institution != "All") {
      data <- data[data$`Hosting Institution` == input$Institution,]
  }
  if (input$Type != "All") {
      data <- data[data$Type == input$Type,]
  }
  if (input$Subject != "All") {
    data <- data[data$`Subject area` == input$Subject,]
  }
  if (input$Access != "All") {
      data <- data[data$`Open Access` == input$Access,]
  }
  
  data
  },
  # 'escape = n' indicates that HTML in column 'n' should be escaped
  # possible values: 2 ('Name'), 9 ('URL')
  options = list(pageLength = 20), escape = 2))
```
