version: "3.7"
services:
  data-collections-explorer:
    image: nfdi4ing-data-collections-explorer:v1
    container_name: nfdi4ing-data-collections-explorer
    ports:
      - 3838:3838
    volumes:
      - ./application:/srv/shiny-server/
      - ./shiny-logs:/var/log/shiny-server/
    restart: unless-stopped
