---
title: "NFDI4Ing Repository Explorer"
author: "KIT / SCC"
date: "23/01/2022"
output:   
    flexdashboard::flex_dashboard:
        theme: spacelab
        orientation: columns
        vertical_layout: fill
        source_code: embed
        logo: NFDI4Ing.png
runtime: shiny
---
<script>
<!-- From StackOverflow question 51600940; this seems to be the easiest solution -->
$('.navbar-logo').wrap('<a href="https://www.nfdi4ing.de">');
</script>

```{r global, include=FALSE}
library(flexdashboard)
library(DT)
library(RCurl)
library(jpeg)
library(readr)


Repositories <- read_delim("Repositories.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)

```

Row {} 
--------------------------------------
#### Select
```{r selection}
fluidRow(
    column(3, selectInput('Type', 'Type:', c( "All", unique(as.character(Repositories$Type))))),
    column(3, selectInput('Institution', 'Hosting Institution:', c( "All", unique(as.character(Repositories$`Hosting Institution`))))),
    column(3, selectInput('Subject', 'Subject Area:', c("All", unique(as.character(Repositories$`Subject area`))))),
    column(3, selectInput('Access', 'Open Access:', c( "All", unique(as.character(Repositories$`Open Access`))))),
    title = "NFDI4Ing Repository Explorer"
)

```


#### Repositories and Collections
```{r rendering}

div(DT::dataTableOutput('x1'), style = "font-size: 100%")
output$x1 = DT::renderDataTable(DT::datatable({
  data <- Repositories
    if (input$Type != "All") {
      data <- data[data$Type == input$Type,]
    } 
  if (input$Institution != "All") {
      data <- data[data$`Hosting Institution` == input$Institution,]
  }
  if (input$Subject != "All") {
    data <- data[data$`Subject area` == input$Subject,]
  }
  if (input$Access != "All") {
      data <- data[data$`Open Access` == input$Access,]
    }
    data 
  
  }, options = list(pageLength = 20))) 

```



